### ISSUE TITLE
随机一卡功能报错

### ISSUE THREAD

**Issue by ElainaFanBoy** [fireinsect/nonebot-plugin-ocgbot-v2#3]
随机一卡
```
07-02 21:40:31 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_ocgbot_v2.ocg) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\lastload\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\ocg.py", line 163, in _
    await send3(js, randomCard)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\libraries\sendAction.py", line 142, in send3
    await func.finish(getPicOnlyMessage(js, num, pics_url))
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\libraries\sendAction.py", line 244, in getPicOnlyMessage
    "file": f"base64://{str(image_to_base64(url), encoding='utf-8')}"
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\libraries\image.py", line 103, in image_to_base64
    img.save(output_buffer, format)
AttributeError: 'str' object has no attribute 'save'
```

**Comment by fireinsect** [comment]
唔，忘写Image打开了，把/libraies/sendAction.py 内第244行url换成Image.open(url) 即可。（或者等我修完出新版本）

**Comment by ElainaFanBoy** [comment]
> 唔，忘写Image打开了，把/libraies/sendAction.py 内第244行url换成Image.open(url) 即可。（或者等我修完出新版本）

辛苦了，不过修改后还是报错了
```
07-02 22:34:45 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_ocgbot_v2.ocg) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\lastload\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\ocg.py", line 163, in _
    await send3(js, randomCard)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\libraries\sendAction.py", line 142, in send3
    await func.finish(getPicOnlyMessage(js, num, pics_url))
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\libraries\sendAction.py", line 244, in getPicOnlyMessage
    "file": f"base64://{str(image_to_base64(url), encoding='utf-8')}"
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\libraries\image.py", line 103, in image_to_base64
    img.save(output_buffer, format)
AttributeError: 'str' object has no attribute 'save'
```

**Comment by fireinsect** [comment]
"file": f"base64://{str(image_to_base64(url), encoding='utf-8')}"
---->
 "file": f"base64://{str(image_to_base64(Image.open(url)), encoding='utf-8')}"

**Comment by ElainaFanBoy** [comment]
> > 唔，忘写Image打开了，把/libraies/sendAction.py 内第244行url换成Image.open(url) 即可。（或者等我修完出新版本）
> 
> 辛苦了，不过修改后还是报错了
> 
> ```
> 07-02 22:34:45 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_ocgbot_v2.ocg) failed.
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 116, in spawn_main
>     exitcode = _main(fd, parent_sentinel)
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 129, in _main
>     return self._bootstrap(parent_sentinel)
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 315, in _bootstrap
>     self.run()
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\lastload\nonebot_plugin_reboot\reloader.py", line 27, in _run
>     _nb_run(*args, **kwargs)
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\__init__.py", line 309, in run
>     get_driver().run(*args, **kwargs)
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
>     uvicorn.run(
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\main.py", line 578, in run
>     server.run()
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\server.py", line 61, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 634, in run_until_complete
>     self.run_forever()
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\windows_events.py", line 321, in run_forever
>     super().run_forever()
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 601, in run_forever
>     self._run_once()
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 1905, in _run_once
>     handle._run()
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
>     await _run_matcher(
> > File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
>     await matcher.run(bot, event, state, stack, dependency_cache)
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
>     await self.simple_run(bot, event, state, stack, dependency_cache)
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
>     await handler(
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
>     return await cast(Callable[..., Awaitable[R]], self.call)(**values)
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\ocg.py", line 163, in _
>     await send3(js, randomCard)
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\libraries\sendAction.py", line 142, in send3
>     await func.finish(getPicOnlyMessage(js, num, pics_url))
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\libraries\sendAction.py", line 244, in getPicOnlyMessage
>     "file": f"base64://{str(image_to_base64(url), encoding='utf-8')}"
>   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\libraries\image.py", line 103, in image_to_base64
>     img.save(output_buffer, format)
> AttributeError: 'str' object has no attribute 'save'
> ```

我改成`"file": f"base64://{str(image_to_base64(Image.open(url)), encoding='utf-8')}"`后依旧报这个错
话说依赖版本可不可以降低一些，我装的时候pyee和numpy它自动给我升级了，然后我htmlrender那个插件就炸了（？），手动降级之后就没事

**Comment by ElainaFanBoy** [comment]
> > > 唔，忘写Image打开了，把/libraies/sendAction.py 内第244行url换成Image.open(url) 即可。（或者等我修完出新版本）
> > 
> > 
> > 辛苦了，不过修改后还是报错了
> > ```
> > 07-02 22:34:45 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_ocgbot_v2.ocg) failed.
> > Traceback (most recent call last):
> >   File "<string>", line 1, in <module>
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 116, in spawn_main
> >     exitcode = _main(fd, parent_sentinel)
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 129, in _main
> >     return self._bootstrap(parent_sentinel)
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 315, in _bootstrap
> >     self.run()
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 108, in run
> >     self._target(*self._args, **self._kwargs)
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\lastload\nonebot_plugin_reboot\reloader.py", line 27, in _run
> >     _nb_run(*args, **kwargs)
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\__init__.py", line 309, in run
> >     get_driver().run(*args, **kwargs)
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
> >     uvicorn.run(
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\main.py", line 578, in run
> >     server.run()
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\server.py", line 61, in run
> >     return asyncio.run(self.serve(sockets=sockets))
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\runners.py", line 44, in run
> >     return loop.run_until_complete(main)
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 634, in run_until_complete
> >     self.run_forever()
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\windows_events.py", line 321, in run_forever
> >     super().run_forever()
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 601, in run_forever
> >     self._run_once()
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 1905, in _run_once
> >     handle._run()
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\events.py", line 80, in _run
> >     self._context.run(self._callback, *self._args)
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
> >     await _run_matcher(
> > > File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
> >     await matcher.run(bot, event, state, stack, dependency_cache)
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
> >     await self.simple_run(bot, event, state, stack, dependency_cache)
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
> >     await handler(
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
> >     return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\ocg.py", line 163, in _
> >     await send3(js, randomCard)
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\libraries\sendAction.py", line 142, in send3
> >     await func.finish(getPicOnlyMessage(js, num, pics_url))
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\libraries\sendAction.py", line 244, in getPicOnlyMessage
> >     "file": f"base64://{str(image_to_base64(url), encoding='utf-8')}"
> >   File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot_plugin_ocgbot_v2\libraries\image.py", line 103, in image_to_base64
> >     img.save(output_buffer, format)
> > AttributeError: 'str' object has no attribute 'save'
> > ```
> 
> 我改成`"file": f"base64://{str(image_to_base64(Image.open(url)), encoding='utf-8')}"`后依旧报这个错 话说依赖版本可不可以降低一些，我装的时候pyee和numpy它自动给我升级了，然后我htmlrender那个插件就炸了（？），手动降级之后就没事

噢我知道咋回事了
